### ISSUE TITLE
[Bug] Sidebar does not expand when i click the button

### ISSUE THREAD

**Issue by SantiGodoy** [creativetimofficial/now-ui-dashboard#16]
### Version
1.5.0
### Reproduction link
https://github.com/SantiGodoy/EditorColaborativoTFG
### Operating System
Windows 10
### Device
Desktop computer
### Browser & Version
Google Chrome 80.0.3987.106
### Steps to reproduce
1. Collapse the sidebar
2. Click the hamburger button to expand the sidebar
### What is expected?
Sidebar expanding after clicking the button
### What is actually happening?
Sidebar not expanding

---
### Solution
Maybe i'm missing some logic in the code, but i think that i have everything in it.
### Additional comments
I have compared my source code with the original project but i don't see any significant difference between them.

**Comment by dragosct** [comment]
Hi, @SantiGodoy! Thank you for using our products and sorry for the late response. Please, can you give us a link to your project to see exactly the problem? 

Regards,
Dragos

**Comment by SantiGodoy** [comment]
Just found my error, i added every .js file except the dashboard one. Pretty dumb, sorry, now it is working!

Thank you!
