### ISSUE TITLE
Fontawesome 5 Icons does not works on achors

### ISSUE THREAD

**Issue by nasirkhan** [creativetimofficial/now-ui-dashboard#2]
I included both the JS ans CSS version of Font Awesome 5 but the icons does not work on Anchor (`<a>`) tags. Though the icons are displaying properly on Buttons. 

Usually these works perfectly with both the `<a>` and `<button>` tags.

Green is an anchor and orange is a button here, 
![screenshot-laravel dev-2018-03-07-12-22-36](https://user-images.githubusercontent.com/396987/37076818-4ecbb57c-2202-11e8-9b85-3511ebb8b506.png)

**Comment by dragosct** [comment]
Hi, @nasirkhan! Thank you for using our product. From what I understand the colors that appear below should be applied only to icons, not the anchor itself right? 

Regards,
Dragos

**Comment by nasirkhan** [comment]
Thanks for responding. i mentioned the color to identify the differences. On the above one the icon is not in the center of the button, but the bottom one is showing perfectly at the center.

**Comment by dragosct** [comment]
Hi! Can you give me your link to see what happened there because I think there is a small css problem? Regads, Dragos

**Comment by nasirkhan** [comment]
Here is the example :
https://nasirkhan.github.io/now-ui-dashboard/examples/font-awesome.html


--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by dragosct** [comment]
Hi, @nasirkhan! You can put on the class .btn the properties: 

```css
    display: inline-flex;
    align-items: center;
```

and on the svg icon you can put the property `margin: 0 auto;` and this will fix the issue for you. 

Regards, 
Dragos

**Comment by nasirkhan** [comment]
Sorry i missed your reply. I added the code and then the icon moved left. check https://nasirkhan.github.io/now-ui-dashboard/examples/font-awesome.html

commit: https://github.com/nasirkhan/now-ui-dashboard/commit/405954fa4b08b93e2897a40040bca22ef82f6fdb

**Comment by nasirkhan** [comment]
facing similar issue with the Now UI Kit also, should i create an another issue there?

**Comment by dragosct** [comment]
Hi! Just add also this property `justify-content: center;`. Regards, Dragos

**Comment by nasirkhan** [comment]
it solves the issue thanks.
