### ISSUE TITLE
Unable to compile scss file

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/now-ui-dashboard#3]
Hi, when i try to include scss file, i got this error message:

`File to import not found or unreadable: mixins/free/buttons.`

and when i check on the mixing file, there is no free folder, can you check?

```
//Components
@import "mixins/free/buttons";
@import "mixins/free/vendor-prefixes";
@import "mixins/free/inputs";
@import "mixins/free/page-header";
@import "mixins/free/dropdown";
@import "mixins/free/cards";
@import "mixins/free/transparency";
```

**Comment by dragosct** [comment]
Hi, @hbinduni! Thank you for using our product. If you use the PRO version yes it was a problem and it was fixed now. Please download again the archive and will work after that. Please, let us know if it works! Regards, Dragos

**Comment by hbinduni** [comment]
Thank you. Confirm it work now.
